### ISSUE TITLE
Sind.R calculates some of the expected proportions incorrectly

### ISSUE THREAD

**Issue by JoniPaakko** [fsotoc/grtools#3]
Due to an indexing problem, half of the expected proportions calculated in sind.R to assess sampling independence are incorrect. I will demonstrate the problem with an example.

This is the confusion matrix given as an example in Multidimensional Signal Detection Theory (Ashy & Soto 2015):

```
ConfusionMatrix = matrix(c(140, 36, 34, 40, 89, 91, 
4, 66, 85, 5, 90, 70, 20, 59, 8, 163), nrow = 4, ncol = 4, byrow=TRUE)
rownames(ConfusionMatrix) = c("A1B1", "A2B1", "A1B2", "A2B2")
colnames(ConfusionMatrix) = c("a1b1", "a2b1", "a1b2", "a2b2")
```

Now, to have  a "ground truth", I calculated all of the expected probabilities by hand and collected them in a "ground truth table":

```
GTT = matrix(nrow = 4, ncol=4)

GTT[1,1] = (140/250 + 34/250) * (140/250 + 36/250)
GTT[1,2] = (36/250 + 40/250) * (36/250 + 140/250)
GTT[1,3] = (34/250 + 140/250) * (34/250 + 40/250)
GTT[1,4] = (40/250 + 36/250) * (40/250 + 34/250)

GTT[2,1] = (89/250 + 4/250) * (89/250 + 91/250)
GTT[2,2] = (91/250 + 66/250) * (91/250 + 89/250)
GTT[2,3] = (4/250 + 89/250) * (4/250 + 66/250)
GTT[2,4] = (66/250 + 91/250) * (66/250 + 4/250)

GTT[3,1] = (85/250 + 90/250) * (85/250 + 5/250)
GTT[3,2] = (5/250 + 70/250) * (5/250 + 85/250)
GTT[3,3] = (90/250 + 85/250) * (90/250 + 70/250)
GTT[3,4] = (70/250 + 5/250) * (70/250 + 90/250)

GTT[4,1] = (20/250 + 8/250) * (20/250 + 59/250)
GTT[4,2] = (59/250 + 163/250) * (59/250 + 20/250)
GTT[4,3] = (8/250 + 20/250) * (8/250 + 163/250)
GTT[4,4] = (163/250 + 59/250) * (163/250 + 8/250)
```

Now, if one uses grtools to calculate sampling independence and then compares this to the "ground truth table", one sees that half of the expected proportions don't match.

```
library(grtools)
results = sumstats_micro(ConfusionMatrix)
t(matrix(round(as.numeric(results$sampling_independence$Expected_p),3), nrow = 4)) == round(GTT, 3)
```

As suggested by Fabian Soto in a personal email, this is fairly easily fixed by changing line 17 in sind.R from 

```
(P[i,2] + P[i,4])),
```

to 

```
(P[i,3] + P[i,4])),
```

**Comment by fsotoc** [comment]
Thank you for catching that bug. I've replaced the code in sind.R so I'm closing this issue.
