### ISSUE TITLE
Collaborate on a Bayesian Python port?

### ISSUE THREAD

**Issue by brianspiering** [fsotoc/grtools#4]
Hey Fabian,

I'm a graduate of the Ashby lab. Over some 🍻, Matthew Crossley @crossley and I talked about creating a Bayesian version of GRT.

I rather do it Python. Thoughts?

Best, 
Brian

**Comment by fsotoc** [comment]
Hi Brian,

Noah Silbert created a hierarchical Bayesian version of the traditional GRT model. He reported that model in [this paper](http://www.academia.edu/download/43971635/silbert_2012_grt_speech_perception.pdf). Is that what you guys were thinking about?

He also has an R package ([mdsdt](https://cran.r-project.org/web/packages/mdsdt/index.html)), but I'm not sure whether he implemented his Bayesian model there.
